# Controlled skill canonicalization & alias dictionary
SKILL_ALIASES = {
    # JavaScript & TypeScript
    "js": "JavaScript",
    "javascript": "JavaScript",
    "ecmascript": "JavaScript",
    "es6": "JavaScript",
    "es6+": "JavaScript",
    "ts": "TypeScript",
    "typescript": "TypeScript",
    
    # Node & Runtime
    "node": "Node.js",
    "nodejs": "Node.js",
    "node.js": "Node.js",
    "node js": "Node.js",
    
    # Frontend Frameworks
    "react": "React",
    "react.js": "React",
    "reactjs": "React",
    "react js": "React",
    "next": "Next.js",
    "next.js": "Next.js",
    "nextjs": "Next.js",
    "vue": "Vue",
    "vue.js": "Vue",
    "vuejs": "Vue",
    "angular": "Angular",
    "angular.js": "Angular",
    "angularjs": "Angular",
    "nuxt": "Nuxt.js",
    "nuxt.js": "Nuxt.js",
    "nuxtjs": "Nuxt.js",
    
    # Styling
    "tailwind": "Tailwind CSS",
    "tailwindcss": "Tailwind CSS",
    "tailwind css": "Tailwind CSS",
    "html5": "HTML",
    "html": "HTML",
    "css3": "CSS",
    "css": "CSS",
    "sass": "Sass",
    "scss": "Sass",
    
    # Python & Frameworks
    "python": "Python",
    "python3": "Python",
    "python 3": "Python",
    "py": "Python",
    "fastapi": "FastAPI",
    "fast api": "FastAPI",
    "django": "Django",
    "flask": "Flask",
    
    # Databases & SQL
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "postgres db": "PostgreSQL",
    "psql": "PostgreSQL",
    "mysql": "MySQL",
    "sqlite": "SQLite",
    "sqlite3": "SQLite",
    "mongodb": "MongoDB",
    "mongo": "MongoDB",
    "redis": "Redis",
    "sql": "SQL",
    "relational database": "SQL",
    "relational databases": "SQL",
    
    # Git & Version Control
    "git": "Git",
    "github": "Git",
    "git/github": "Git",
    "gitlab": "Git",
    
    # DevOps & Cloud
    "docker": "Docker",
    "dockerfile": "Docker",
    "docker compose": "Docker",
    "docker-compose": "Docker",
    "containerization": "Docker",
    "containers": "Docker",
    "k8s": "Kubernetes",
    "kubernetes": "Kubernetes",
    "aws": "AWS",
    "amazon web services": "AWS",
    "ec2": "AWS",
    "s3": "AWS",
    "gcp": "GCP",
    "google cloud": "GCP",
    "google cloud platform": "GCP",
    "azure": "Azure",
    "microsoft azure": "Azure",
    "ci/cd": "CI/CD",
    "cicd": "CI/CD",
    "ci cd": "CI/CD",
    "github actions": "GitHub Actions",
    
    # Languages
    "c++": "C++",
    "cpp": "C++",
    "c#": "C#",
    "csharp": "C#",
    "c sharp": "C#",
    "golang": "Go",
    "go": "Go",
    "rust": "Rust",
    "java": "Java",
    "ruby": "Ruby",
    "php": "PHP",
    
    # API & Architecture
    "rest": "REST API",
    "rest api": "REST API",
    "rest apis": "REST API",
    "restful": "REST API",
    "restful api": "REST API",
    "restful apis": "REST API",
    "graphql": "GraphQL",
    "microservices": "Microservices",
    
    # Data Engineering & Messaging
    "snowflake": "Snowflake",
    "airflow": "Airflow",
    "apache airflow": "Airflow",
    "kafka": "Kafka",
    "apache kafka": "Kafka",
    "etl": "ETL",
    "data pipeline": "ETL",
    "data pipelines": "ETL",
    "spark": "Spark",
    "apache spark": "Spark",
    "hadoop": "Hadoop",
    "apache hadoop": "Hadoop",

    # Monitoring & Infra Tools
    "prometheus": "Prometheus",
    "grafana": "Grafana",
    "helm": "Helm",
    "vault": "Vault",
    "hashicorp vault": "Vault",
    
    # AI / ML / Data
    "ml": "Machine Learning",
    "machine learning": "Machine Learning",
    "deep learning": "Deep Learning",
    "nlp": "NLP",
    "natural language processing": "NLP",
    "ai": "Artificial Intelligence",
    "artificial intelligence": "Artificial Intelligence",
    "genai": "Artificial Intelligence",
    "gen ai": "Artificial Intelligence",
    "generative ai": "Artificial Intelligence",
    "llm": "Artificial Intelligence",
    "llms": "Artificial Intelligence",
    "pytorch": "PyTorch",
    "tensorflow": "TensorFlow",
    "scikit-learn": "Scikit-learn",
    "sklearn": "Scikit-learn",
    "pandas": "Pandas",
    "numpy": "NumPy",
}

KNOWN_SKILLS = [
    "Python", "Java", "C++", "C", "C#", "JavaScript", "TypeScript", "Go", "Rust", "Ruby", "PHP", "SQL",
    "React", "Angular", "Vue", "HTML", "CSS", "Tailwind CSS", "Sass", "Next.js", "Nuxt.js",
    "Node.js", "Express", "FastAPI", "Django", "Flask", "Spring Boot", "Ruby on Rails",
    "PostgreSQL", "MySQL", "MongoDB", "Redis", "SQLite", "Oracle", "Cassandra", "Elasticsearch", "Snowflake",
    "AWS", "Azure", "GCP", "Docker", "Kubernetes", "GitHub Actions", "CI/CD", "Jenkins", "Terraform", "Ansible",
    "Prometheus", "Grafana", "Helm", "Vault",
    "Machine Learning", "Deep Learning", "NLP", "Computer Vision", "Artificial Intelligence",
    "PyTorch", "TensorFlow", "Keras", "Scikit-learn",
    "Pandas", "NumPy", "Matplotlib", "Power BI", "Tableau", "Spark", "Hadoop", "Airflow", "Kafka", "ETL",
    "REST API", "GraphQL", "Microservices", "Linux", "Unix", "Bash", "Git"
]
